#!/bin/bash
set -x

EXTRA_ARGS="$@"

function convert() {
	echo "$1.dictionary"
	pyglossary "$1.dictionary" "$1.txt" \
		'--read-options=html_full=false' $EXTRA_ARGS
	echo
}

convert "002-simple"

convert "006-en-oxfjord_v10.5_c0_t0"
convert "006-en-oxfjord_v10.5_c1_t0"

convert "006-en-oxfjord_v10.6_c0_t0"
convert "006-en-oxfjord_v10.6_c0_t1"

convert "006-en-oxfjord_v10.6_c0_t3"
convert "006-en-oxfjord_v10.6_c1_t0"
convert "006-en-oxfjord_v10.6_c1_t1"

convert "006-en-oxfjord_v10.6_c1_t3"
convert "006-en-oxfjord_v10.6_c2_t0"
convert "006-en-oxfjord_v10.6_c2_t1"

convert "006-en-oxfjord_v10.6_c2_t3"

convert "006-en-oxfjord_v10.11_c2_t3"

convert "006-en-oxfjord_v10.6_c0_t2"
# previously: [ERROR] WRONG priority or parental control:44 (section: 0x15e), skipping KeyText.data file


convert "006-en-oxfjord_v10.6_c1_t2"
# previously: [ERROR] WRONG priority or parental control:44 (section: 0x15e), skipping KeyText.data file

convert "006-en-oxfjord_v10.6_c2_t2"
# previously:
#  File "/home/s/pyglossary/pyglossary/plugins/appledict_bin/appledict_file_tools.py", line 55, in read_2_bytes_here
#    return ord(higher_byte) * 0x100 + ord(lower_byte)
# TypeError: ord() expected a character, but string of length 0 found



# "006-en-oxfjord_v10.5_c0_t0.txt": "2d3844bf",
# "006-en-oxfjord_v10.5_c1_t0.txt": "2d3844bf",
# "006-en-oxfjord_v10.6_c0_t0.txt": "2d3844bf",
# "006-en-oxfjord_v10.6_c0_t1.txt": "2d3844bf",
# "006-en-oxfjord_v10.6_c0_t3.txt": "2d3844bf",
# "006-en-oxfjord_v10.6_c1_t0.txt": "2d3844bf",
# "006-en-oxfjord_v10.6_c1_t1.txt": "2d3844bf",
# "006-en-oxfjord_v10.6_c1_t3.txt": "2d3844bf",
# "006-en-oxfjord_v10.6_c2_t0.txt": "2d3844bf",
# "006-en-oxfjord_v10.6_c2_t1.txt": "2d3844bf",
# "006-en-oxfjord_v10.6_c2_t3.txt": "2d3844bf",
# "006-en-oxfjord_v10.11_c2_t3.txt": "2d3844bf",

# "006-en-oxfjord_v10.6_c0_t2.txt": "8b372838",
# "006-en-oxfjord_v10.6_c1_t2.txt": "8b372838",
# "006-en-oxfjord_v10.6_c2_t2.txt": "8b372838",
