#!/bin/bash

pyglossary "002-simple.dictionary" "002-simple.txt"

pyglossary "006-en-oxfjord_v10.5_c0_t0.dictionary" "006-en-oxfjord_v10.5_c0_t0.txt"
pyglossary "006-en-oxfjord_v10.5_c1_t0.dictionary" "006-en-oxfjord_v10.5_c1_t0.txt"

pyglossary "006-en-oxfjord_v10.6_c0_t0.dictionary" "006-en-oxfjord_v10.6_c0_t0.txt"
pyglossary "006-en-oxfjord_v10.6_c0_t1.dictionary" "006-en-oxfjord_v10.6_c0_t1.txt"

pyglossary "006-en-oxfjord_v10.6_c0_t3.dictionary" "006-en-oxfjord_v10.6_c0_t3.txt"
pyglossary "006-en-oxfjord_v10.6_c1_t0.dictionary" "006-en-oxfjord_v10.6_c1_t0.txt"
pyglossary "006-en-oxfjord_v10.6_c1_t1.dictionary" "006-en-oxfjord_v10.6_c1_t1.txt"

pyglossary "006-en-oxfjord_v10.6_c1_t3.dictionary" "006-en-oxfjord_v10.6_c1_t3.txt"
pyglossary "006-en-oxfjord_v10.6_c2_t0.dictionary" "006-en-oxfjord_v10.6_c2_t0.txt"
pyglossary "006-en-oxfjord_v10.6_c2_t1.dictionary" "006-en-oxfjord_v10.6_c2_t1.txt"

pyglossary "006-en-oxfjord_v10.6_c2_t3.dictionary" "006-en-oxfjord_v10.6_c2_t3.txt"

pyglossary "006-en-oxfjord_v10.11_c2_t3.dictionary" "006-en-oxfjord_v10.11_c2_t3.txt"

